// menu action types
export const FETCH_MENU_REQUEST = "FETCH_MENU_REQUEST";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";
export const SAVE_MENU = "SAVE_MENU";

//account
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";
export const LOGOUT_HANDLER = "LOGOUT_HANDLER";

//productlist
export const FETCH_PRODUCTLIST_REQUEST = "FETCH_PRODUCTLIST_REQUEST";
export const FETCH_PRODUCTLIST_SUCCESS = "FETCH_PRODUCTLIST_SUCCESS";
export const FETCH_PRODUCTLIST_FAILURE = "FETCH_MENU_FAILURE";

export const FETCH_PAGINATION_REQUEST = "FETCH_PAGINATION_REQUEST";
export const FETCH_PAGINATION_SUCCESS = "FETCH_PAGINATION_SUCCESS";
export const FETCH_PAGINATION_FAILURE = "FETCH_PAGINATION_FAILURE";

// get meta data
export const GET_META_DATA = "GET_META_DATA";
